# ============================================================================
# simulate_data.R
#
# NOTE - this is strictly illustrative for the dashboard examples 
# and generated by Claude. It is based on my ABCD simulation code and meta-analysis
# data cleaning scripts, but it is not necessarily a good example of how to 
# simulate meta-analysis data. Do not base any real project simulation code off of this!!!
#
# Generates a simulated IPD co-etiology dataset for the flexdashboard lesson.
#
# Data structure mirrors the real IPD data (see str(data) and prep_ipd.R):
#   - pathogen_new   : continuous TAC quantity = (35 - CT) / 3.322
#                      Zero-inflated: 0 when not detected, positive otherwise.
#                      Distribution shapes from the lab's 00_simulate_data.R.
#   - pathogen_bin   : 1 if detected by TAC (quantity > 0), 0 otherwise
#   - pathogen_tac_attr : 1 if attributable (quantity above study-specific
#                         threshold, approx. AFE > 0.5), 0 otherwise
#
# Five studies: ABCD, EFGH, GEMS, VIDA, MALED
# Twelve pathogens matching real column names (_new / _bin / _tac_attr)
#
# Output: data/ipd_sim.Rds
#
# Run once before opening any lesson dashboard:
#   source("simulate_data.R")
# ============================================================================

library(dplyr)

set.seed(12345)

# ── Pathogen names and display labels ────────────────────────────────────────
# Naming matches real data: shigella_new, rotavirus_new, etc.
PATHOGENS <- c(
  "shigella", "rotavirus", "norovirus_gii", "adenovirus", "astrovirus",
  "sapovirus", "st_etec", "campylobacter", "tepec",
  "v_cholerae", "salmonella", "cryptosporidium"
)

pathogen_labels <- c(
  shigella        = "Shigella",
  rotavirus       = "Rotavirus",
  norovirus_gii   = "Norovirus GII",
  adenovirus      = "Adenovirus",
  astrovirus      = "Astrovirus",
  sapovirus       = "Sapovirus",
  st_etec         = "ST-ETEC",
  campylobacter   = "C. jejuni/coli",
  tepec           = "tEPEC",
  v_cholerae      = "V. cholerae",
  salmonella      = "Salmonella",
  cryptosporidium = "Cryptosporidium"
)

# ── Study metadata ─────────────────────────────────────────────────────────────
STUDIES <- c("ABCD", "EFGH", "GEMS", "VIDA", "MALED")

study_meta <- data.frame(
  study    = STUDIES,
  n        = c(250, 200, 250, 150, 150),
  msd_prob = c(0.72, 0.68, 0.78, 0.65, 0.70),
  age_mean = c(11.6, 15.6, 17.8, 19.2, 12.7),  # mean age in months
  age_sd   = c(5.27,  7.41,  12.6, 12.2, 6.86),
  haz_mean = c(-1.46, -1.19, -1.33, -1.12, -1.33),  # mean baseline HAZ
  haz_sd   = c(1.35,  1.22,  1.29,  1.16,  1.19),
  stringsAsFactors = FALSE
)


# ── Pathogen quantity distributions ──────────────────────────────────────────
# The _new columns are (35 - CT) / 3.322, so they are:
#   - Exactly 0 when the pathogen is not detected (CT = 35 or no amplification)
#   - Positive and continuous when detected, with pathogen-specific shapes
#
# Parameters come from 00_simulate_data.R (lab simulation script).
# Each pathogen has:
#   det_prob   : P(detected, i.e. quantity > 0)
#   dist       : distribution family for the positive part
#   params     : named list of distribution parameters
#   attr_cutoff: quantity threshold above which the case is considered
#                attributable (approximates AFE > 0.5 from real attribution)
#
# Attribution thresholds are approximate — in the real data these come from
# study-specific logistic models, but a fixed quantity cutoff gives the
# right qualitative structure for teaching purposes.

pathogen_specs <- list(
  shigella = list(
    det_prob    = 0.19,
    dist        = "weibull",
    params      = list(shape = 1.86, scale = 3.06),
    attr_cutoff = 2.0   # roughly top ~60% of detected → attributable
  ),
  rotavirus = list(
    det_prob    = 0.24,
    dist        = "gamma",
    params      = list(shape = 3.90, rate = 1.25),
    attr_cutoff = 2.5
  ),
  norovirus_gii = list(
    det_prob    = 0.19,
    dist        = "uniform",
    params      = list(min = 0, max = 6),
    attr_cutoff = 3.0
  ),
  adenovirus = list(
    det_prob    = 0.19,
    dist        = "gamma",
    params      = list(shape = 1.19, rate = 0.43),
    attr_cutoff = 1.5
  ),
  astrovirus = list(
    det_prob    = 0.09,
    dist        = "uniform",
    params      = list(min = 0, max = 6),
    attr_cutoff = 3.0
  ),
  sapovirus = list(
    det_prob    = 0.17,
    dist        = "gamma",
    params      = list(shape = 2.34, rate = 0.93),
    attr_cutoff = 2.0
  ),
  st_etec = list(
    det_prob    = 0.23,
    dist        = "uniform",
    params      = list(min = 0, max = 7),
    attr_cutoff = 3.5
  ),
  campylobacter = list(
    det_prob    = 0.34,
    dist        = "weibull",
    params      = list(shape = 1.82, scale = 2.73),
    attr_cutoff = 2.0
  ),
  tepec = list(
    det_prob    = 0.22,
    dist        = "uniform",
    params      = list(min = 0, max = 6.5),
    attr_cutoff = 3.0
  ),
  v_cholerae = list(
    det_prob    = 0.03,
    dist        = "gamma",
    params      = list(shape = 1.86, rate = 1.06),
    attr_cutoff = 1.5
  ),
  salmonella = list(
    det_prob    = 0.01,
    dist        = "weibull",
    params      = list(shape = 1.28, scale = 1.93),
    attr_cutoff = 1.5
  ),
  cryptosporidium = list(
    det_prob    = 0.20,
    dist        = "gamma",
    params      = list(shape = 2.21, rate = 0.77),
    attr_cutoff = 2.0
  )
)

# ── Quantity simulation helper ────────────────────────────────────────────────
# Generates n continuous TAC quantities for one pathogen.
# Returns 0 for undetected cases, a positive draw from the specified
# distribution for detected cases — exactly the structure of _new in real data.

sim_quantity <- function(n, spec) {
  detected <- rbinom(n, 1, spec$det_prob)
  qty <- numeric(n)
  
  n_det <- sum(detected)
  if (n_det > 0) {
    qty[detected == 1] <- switch(
      spec$dist,
      gamma   = rgamma(n_det,
                       shape = spec$params$shape,
                       rate  = spec$params$rate),
      weibull = rweibull(n_det,
                         shape = spec$params$shape,
                         scale = spec$params$scale),
      uniform = runif(n_det,
                      min = spec$params$min,
                      max = spec$params$max)
    )
  }
  
  round(qty, 3)
}

# ── Generate data ─────────────────────────────────────────────────────────────
study_blocks <- lapply(seq_len(nrow(study_meta)), function(i) {
  
  s  <- study_meta$study[i]
  ni <- study_meta$n[i]
  
  # Covariates — match real data variable names
  d <- data.frame(
    study   = s,
    MSD     = rbinom(ni, 1, study_meta$msd_prob[i]),
    age     = pmax(2L, pmin(59L,
                            round(rnorm(ni, study_meta$age_mean[i], study_meta$age_sd[i])))),
    enr_haz = round(rnorm(ni, study_meta$haz_mean[i], study_meta$haz_sd[i]), 2),
    stringsAsFactors = FALSE
  )
  
  # Simulate a follow-up HAZ outcome (weakly related to enr_haz and age)
  d$final_haz <- round(
    d$enr_haz * 0.70 +
      rnorm(ni, mean = -0.05, sd = 0.55),
    2
  )
  
  # Pathogen columns — for each pathogen generate:
  #   pathogen_new      : continuous quantity (zero = not detected)
  #   pathogen_bin      : 1 if detected (quantity > 0)
  #   pathogen_tac_attr : 1 if attributable (quantity > cutoff)
  for (p in PATHOGENS) {
    spec <- pathogen_specs[[p]]
    qty  <- sim_quantity(ni, spec)
    
    d[[paste0(p, "_new")]]      <- qty
    d[[paste0(p, "_bin")]]      <- as.integer(qty > 0)
    d[[paste0(p, "_tac_attr")]] <- as.integer(qty > spec$attr_cutoff)
  }
  
  d
})

ipd_sim <- do.call(rbind, study_blocks)
rownames(ipd_sim) <- NULL

# ── Save ──────────────────────────────────────────────────────────────────────
if (!dir.exists("data")) dir.create("data")
saveRDS(ipd_sim, "data/ipd_sim.Rds")

message(
  "Saved data/ipd_sim.Rds\n",
  "  Rows    : ", nrow(ipd_sim), "\n",
  "  Columns : ", ncol(ipd_sim), "\n",
  "  Studies : ",
  paste(names(table(ipd_sim$study)),
        table(ipd_sim$study), sep = "=", collapse = "  ")
)

# Quick sanity check — print attributable prevalence per pathogen
prev <- sapply(PATHOGENS, function(p)
  round(mean(ipd_sim[[paste0(p, "_tac_attr")]] == 1, na.rm = TRUE), 3))
message("\nAttributable prevalence (all cases):")
print(prev)

